name: ci

on:
  push:
    branches: ["main", "master"]
  pull_request:

permissions:
  contents: read

jobs:
  secrets:
    name: secrets-scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Gitleaks
        uses: gitleaks/gitleaks-action@v2

  terraform:
    name: terraform-validate
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: aws-content-pipeline
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform fmt
        run: terraform fmt -check -recursive
      - name: Terraform init (no backend)
        run: terraform init -backend=false
      - name: Terraform validate
        run: terraform validate

  tfsec:
    name: terraform-security
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: tfsec
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          working_directory: aws-content-pipeline
          additional_args: --minimum-severity MEDIUM

  python:
    name: python-tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project:
          - editorbot-stack/editorBot
          - editorbot-stack/dialect_mediator
    defaults:
      run:
        working-directory: ${{ matrix.project }}
    env:
      TELEGRAM_BOT_TOKEN: dummy
      GEMINI_API_KEY: dummy
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: |
            editorbot-stack/editorBot/requirements*.txt
            editorbot-stack/dialect_mediator/requirements*.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then python -m pip install -r requirements-dev.txt; fi
      - name: Run tests
        run: python -m pytest -q
      - name: Ruff
        run: python -m ruff check .
      - name: Black
        run: python -m black --check .

  python-security:
    name: python-security
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project:
          - editorbot-stack/editorBot
          - editorbot-stack/dialect_mediator
    defaults:
      run:
        working-directory: ${{ matrix.project }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: |
            editorbot-stack/editorBot/requirements*.txt
            editorbot-stack/dialect_mediator/requirements*.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi
          python -m pip install pip-audit
      - name: pip-audit
        run: python -m pip_audit --severity medium
